### ISSUE TITLE
关于... 数据表命名规范

### ISSUE THREAD

**Issue by wi1dcard** [InteractivePlus/OPENAPI2019-docs#1]
![image](https://user-images.githubusercontent.com/25447002/43376452-6671acb0-93ed-11e8-892b-6688c7e5d8ba.png)

MySQL Internals Manual - 26.1.1 Coding Style

**Comment by realquantumcookie** [comment]
已在 c3daaf3c65076c2a3c2f49e634ad43a8b7e6d805 中修复.

**Comment by wi1dcard** [comment]
小写+下划线吧

**Comment by realquantumcookie** [comment]
下划线，不存在的
